# Generated by Django 3.2.4 on 2021-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datevssessions',
            name='id',
        ),
        migrations.AlterField(
            model_name='datevssessions',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
