# Generated by Django 3.2.4 on 2021-06-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0002_auto_20210613_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateVsSessions',
            new_name='DateVsSessionsModel',
        ),
    ]
