# Generated by Django 3.2.4 on 2021-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0003_rename_datevssessions_datevssessionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertypemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitor', models.CharField(max_length=20)),
                ('time', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'visitor')},
            },
        ),
    ]
