# Generated by Django 3.2.4 on 2021-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0004_usertypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularvisitormodel',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('visitor', models.CharField(max_length=20)),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Repeatedvisitormodel',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('visitor', models.CharField(max_length=20)),
                ('time', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usertypemodel',
        ),
    ]
