# Generated by Django 3.2.4 on 2021-06-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0005_auto_20210615_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regularvisitormodel',
            new_name='Newvisitormodel',
        ),
    ]
